# .github/workflows/ci-build.yml
name: CI - Build & Push Image

on:
  push:
    branches: [ master ]

jobs:
  train-test-build:
  environment: Testing
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: python train.py

      - uses: actions/upload-artifact@v4
        with:
          name: iris-model
          path: model/

      - uses: actions/download-artifact@v4
        with:
          name: iris-model
          path: model/

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} |
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - run: docker build -t mlops-iris:test .

      - run: |
          docker tag mlops-iris:test ${{ secrets.ECR_REPO }}:latest
          docker push ${{ secrets.ECR_REPO }}:latest
