name: MLOps CI Docker ECR Pipeline

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "model/**"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "world"

  build-train:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python train.py

    #  - name: Upload trained model
    #    uses: actions/upload-artifact@v4
    #    with:
    #       name: iris-model
    #       path: model/

      - name: Commit trained model
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add model/
          git diff --cached --quiet || git commit -m "ci: update trained model"
          git push

  docker-test-push:
    needs: build-train
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Build Docker image
        run: docker build -t mlops-iris:test .

      - name: Run container for testing
        run: |
          docker run -d --name iris-test -p 8000:8000 mlops-iris:test
          sleep 10

      - name: Cleanup test container
        run: |
          docker stop iris-test
          docker rm iris-test

      - name: Tag & Push image to ECR
        run: |
          docker tag mlops-iris:test ${{ secrets.ECR_REPO }}:v1
          docker push ${{ secrets.ECR_REPO }}:v1
