name: Hello world

on:
  push

jobs:
  Test-job:
    runs-on: ubuntu-latest

    steps:
     - name: Hello world
       run: "echo world"

  Build-job:
    runs-on: ubuntu-latest
    needs: Test-job
    steps:

     - name: checkout code
       uses: actions/checkout@v4

     - name: Set up Python
       uses: actions/setup-python@v5
       with:
          python-version: "3.10"

     - name: Installing dependencies
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

     - name: Training the model
       run: |
        python train.py

    #  - name: Upload trained model
    #    uses: actions/upload-artifact@v4
    #    with:
    #       name: iris-model
    #       path: model/

     - name: Commit trained model
       run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add model/
          git diff --cached --quiet || git commit -m "ci: update trained model"

          git push

  docker-test:
    needs: Build-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mlops-iris:test .

      - name: Run container
        run: |
          docker run -d \
            --name iris-test \
            -p 8000:8000 \
            mlops-iris:test

      - name: Wait for API
        run: sleep 10

      - name: Test API with curl
        run: |
          curl -f http://localhost:8000/
          curl -f -X POST http://localhost:8000/predict \
            -H "Content-Type: application/json" \
            -d '{"features":[5.1,3.5,1.4,0.2]}'

      - name: Cleanup container
        run: |
          docker stop iris-test
          docker rm iris-test   
      
